### ISSUE TITLE
能否提供训练好的参数文件

### ISSUE THREAD

**Issue by wangchangquan** [zhangfuyang/rl_CARLA#10]
你好，我跑了几天，发现效果还是很不太好，只用到了DDPG。你能否能提供训练好的参数呢？ 还有你提到了，使用Imitation ，效果会更好，那么怎样使用imitation呢？谢谢

**Comment by zhangfuyang** [comment]
训练好的参数在models文件夹内。imitation的效果确实会更好一些，请参考https://github.com/carla-simulator/imitation-learning 这个repo。
