### ISSUE TITLE
The car doesn't move

### ISSUE THREAD

**Issue by Yiquan-lol** [zhangfuyang/rl_CARLA#13]
Hello, I'm running DDPG main.py, but the car doesn't move
What should I do, please

**Comment by zhangfuyang** [comment]
can you specify what platform you are using? Not sure if some settings cause the problem. As far as I remember, I used ubuntu16.04 + carla0.8 + tf1.12. This setting should work.

**Comment by Yiquan-lol** [comment]
> can you specify what platform you are using? Not sure if some settings cause the problem. As far as I remember, I used ubuntu16.04 + carla0.8 + tf1.12. This setting should work.

ubuntu16.04 + carla0.82 + tf1.14

**Comment by Yiquan-lol** [comment]
> can you specify what platform you are using? Not sure if some settings cause the problem. As far as I remember, I used ubuntu16.04 + carla0.8 + tf1.12. This setting should work.

ubuntu16.04 + carla0.8 + tf1.14

**Comment by Yiquan-lol** [comment]
> can you specify what platform you are using? Not sure if some settings cause the problem. As far as I remember, I used ubuntu16.04 + carla0.8 + tf1.12. This setting should work.

The speed on the simulation interface is 0

**Comment by zhangfuyang** [comment]
does inference work? run "python test_ddpg.py -model_path='models/'"

**Comment by Yiquan-lol** [comment]
> > can you specify what platform you are using? Not sure if some settings cause the problem. As far as I remember, I used ubuntu16.04 + carla0.8 + tf1.12. This setting should work.
> 
> ubuntu16.04 + carla0.8 + tf1.14



> can you specify what platform you are using? Not sure if some settings cause the problem. As far as I remember, I used ubuntu16.04 + carla0.8 + tf1.12. This setting should work.




> does inference work? run "python test_ddpg.py -model_path='models/'"

I can see the car moving

**Comment by Yiquan-lol** [comment]
> does inference work? run "python test_ddpg.py -model_path='models/'"
I can see the car moving

**Comment by Yiquan-lol** [comment]
> does inference work? run "python test_ddpg.py -model_path='models/'"

I can see the car moving

**Comment by zhangfuyang** [comment]
mmm, so not sure what causes the no movement of the car. Currently, I don't have the environment on my device, so I couldn't test it. I will leave the issue open, hope someone also has this problem and will share a solution.

Sorry for being useless...

**Comment by Yiquan-lol** [comment]
> mmm, so not sure what causes the no movement of the car. Currently, I don't have the environment on my device, so I couldn't test it. I will leave the issue open, hope someone also has this problem and will share a solution.
> 
> Sorry for being useless...
I found your old code on https://github.com/zhangfuyang/DDPG-CARLA, I tried to run the ddpg_main. py, but each Episode the car move a little and the Episode is over.  I wonder if it's because I just started training

**Comment by zhangfuyang** [comment]
Ah, good point. Could be that reason. I remember I trained the network for like two days. In the beginning, it could be very abnormal behaviors.

**Comment by Yiquan-lol** [comment]
> Ah, good point. Could be that reason. I remember I trained the network for like two days. In the beginning, it could be very abnormal behaviors.

Yeah. The car was able to move after a night of training.  I see Max_Episode=1000000 in the parameter, I want to know how long the training takes

**Comment by zhangfuyang** [comment]
i don't know how many epochs exactly. Roughly, I used a k80 gpu, and trained 2 days.
