### ISSUE TITLE
LogCarla: Error

### ISSUE THREAD

**Issue by Yiquan-lol** [zhangfuyang/rl_CARLA#14]
Hello, after running DDPG_main for some time
LogSpawn: Warning: SpawnActor failed because of collision at the spawn location [X=24410.000 Y=-195.998 Z=3943.062] for [DodgeChargePolice_C]"
LogCarla: Error: Requested 20 vehicles, but we mere only able to spawn 20
What's going on here，please

**Comment by zhangfuyang** [comment]
It sounds like an issue from Carla engine. Maybe try to decrease the number of vehicles, or just load current ckpt and resume training
