### ISSUE TITLE
What do you use as input for the network?

### ISSUE THREAD

**Issue by qiaoxianfeng** [zhangfuyang/rl_CARLA#15]
I see that you are not directly using RGB images as input, so what do you use as input to the network?

**Comment by zhangfuyang** [comment]
I used a pre-trained network to encode feature vector. which is pretrained by imitation learning. 

There is the code for computing the feature. https://github.com/zhangfuyang/rl_CARLA/blob/master/environment/imitation/imitation_learning.py#L62

**Comment by qiaoxianfeng** [comment]
Can you explain in detail what some feature vectors refer to? Is the street and vehicle information extracted from the RGB image?
