### ISSUE TITLE
Actor网络输入

### ISSUE THREAD

**Issue by Yiquan-lol** [zhangfuyang/rl_CARLA#16]
您的Actor网络输入为512维度的特征+5个车辆自身信息，特征是对RGB图像进行卷积处理和全连接层后得到的，请问特征是分类信息吗

**Comment by zhangfuyang** [comment]
特征是下图这个模型的中间层(白色矩形表示的向量)。这整个模型(图中的卷积层+全连接层)是通过模仿学习预训练的。训练好后直接拿白色矩形作为强化学习的网络输入。
![image](https://user-images.githubusercontent.com/26685632/89706490-105b8880-d91b-11ea-9432-dd037ad9fadb.png)
