### ISSUE TITLE
训练时间

### ISSUE THREAD

**Issue by Yiquan-lol** [zhangfuyang/rl_CARLA#18]
您好，您在ddpg_main.py中设置Max_pisode为200000，请问需要多长时间训练结束

**Comment by zhangfuyang** [comment]
具体时间我已经不太记得了。我设置的最大max_episode是远远大于实际的训练轮数。你可以观察下网络测试的效果，如果已经收敛，就可以停止训练。

**Comment by Yiquan-lol** [comment]
test_ddpg中使用的网络权重是您训练好的吧，请问在哪里

**Comment by Yiquan-lol** [comment]
您在代码中是否使用了模仿学习预训练的模型，请问在哪

**Comment by zhangfuyang** [comment]
ddpg: https://github.com/zhangfuyang/rl_CARLA/tree/master/models

imitation: https://github.com/zhangfuyang/rl_CARLA/tree/master/environment/imitation/model

**Comment by Yiquan-lol** [comment]
您在代码中是否使用了模仿学习预训练的模型

**Comment by zhangfuyang** [comment]
有

**Comment by Yiquan-lol** [comment]
control中brake的值是负值吗，carla官方文档是正值啊  请问是您在文件中修改的吗

**Comment by zhangfuyang** [comment]
是的 我把brake和throttle设置成一个连续的action，正值为加速 负值为刹车
