### ISSUE TITLE
超参数

### ISSUE THREAD

**Issue by q1997** [zhangfuyang/rl_CARLA#20]
您好，您训练好的DDPG模型看起来效果很好，而且训练的步数远没有超参数中设置的那么多，请问您当初在训练时设置的超参数可以分享一下吗

**Comment by zhangfuyang** [comment]
我记得我设计的超参数就是现在文件中的超参数。当时是看训练收敛了就手动停止了。设置的训练步数确实过大。不需要训练那么久

**Comment by q1997** [comment]
请问您收敛的标准是什么？ 另外您提到使用了模仿学习，我在代码中看到您使用了。   没有使用模仿学习的代码请问在哪，我想对比一下实验结果

**Comment by zhangfuyang** [comment]
收敛的标准是根据每一次运行获得的reward值(多跑几次取平均)。

模仿学习的代码是https://github.com/carla-simulator/imitation-learning
