### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by Exasor** [zhangfuyang/rl_CARLA#21]
抱歉刚接触github问的可能比较傻瓜，请问这个项目是比较基础的DDPG-CARLA代码吗，刚接触DDPG想从基础的程序学起，之前看到一些都比较复杂

**Comment by zhangfuyang** [comment]
算法本身不算复杂，就是经典的DDPG。但是因为需要跑在carla环境下，所以整体代码还是有点复杂。如果是刚开始的话，建议从更简洁的环境开始，比如gym之类的。github上有很多运行在gym上强化学习的examples。可以学习借鉴。

祝好

**Comment by Exasor** [comment]
非常感谢！
