### ISSUE TITLE
预训练  

### ISSUE THREAD

**Issue by q1997** [zhangfuyang/rl_CARLA#22]
您在代码中使用了预训练网络，请问没有预训练的网络您可以公开吗

**Comment by zhangfuyang** [comment]
网络在https://github.com/zhangfuyang/rl_CARLA/blob/master/environment/imitation/imitation_learning_network.py

**Comment by Yiquan-lol** [comment]
我也有同样的问题   您在代码中使用了预训练的网络  我看到您在readme文件中比较了三个结果，其中有没有使用预训练网络的实验  请问您可以公开一下没有使用预训练网络的代码吗
