### ISSUE TITLE
Non-player agents 

### ISSUE THREAD

**Issue by Yiquan-lol** [zhangfuyang/rl_CARLA#23]
在carla_sever_pb2.py中我看到您对PlayMeasurement的设置,请问Nonplayer您是否也进行了设置

**Comment by zhangfuyang** [comment]
我记忆中这个文件是carla0.8.4官方文件，是用来连接Carla引擎和python程序的。实际运行中只需要简单的设置(例如 https://github.com/zhangfuyang/rl_CARLA/blob/master/environment/env.py#L93 )。
carla0.8.4我记得好像是不支持设置NPC的。0.9之后的版本支持。

**Comment by Yiquan-lol** [comment]
可能是我没表达清楚。我在carla stable版本（0.8.2）的官方文档中看到是可以获取周围车辆、红绿灯等NPC的位置、状态信息的

**Comment by zhangfuyang** [comment]
I see. 不过我并没有使用这些NPC的信息

**Comment by Yiquan-lol** [comment]
您提到过有一个0.8.4的官方文档，也就是说您Carla版本用的是0.8.4而不是0.8.2？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangfuyang/rl_CARLA"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月20日(星期天) 凌晨0:55
收件人:&nbsp;"zhangfuyang/rl_CARLA"<rl_CARLA@noreply.github.com&gt;;
抄送:&nbsp;"酒醒何处"<956134865@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangfuyang/rl_CARLA] Non-player agents  (#23)





 
I see. 不过我并没有使用这些NPC的信息

**Comment by zhangfuyang** [comment]
Ah sorry. 是0.8.2 我说错了

**Comment by Yiquan-lol** [comment]
非常感谢
