### ISSUE TITLE
读取训练好的模型

### ISSUE THREAD

**Issue by tjtjk** [zhangfuyang/rl_CARLA#29]
您好，我在您的代码中看到  当训练的时候，要读取模仿学习预训练的模型 ，但是在测试的时候却没有读取。 我查看了ddpg训练好的模型，里面没有有关卷积的key  
请问在测试的时候是否读取了模仿学习的模型

**Comment by zhangfuyang** [comment]
测试的时候不需要再读取模仿学习的模型，模仿学习是用来pretrain

**Comment by tjtjk** [comment]
您使用的模仿学习是用来预训练特征提取的部分吗  但是测试的模型中没有特征提取的权重

**Comment by zhangfuyang** [comment]
不好意思，最近事情有点多。
其实是有load 特征提取的权重的。在https://github.com/zhangfuyang/rl_CARLA/blob/968d106d55beca986324a52856f84c72d94ce3fc/src/agent/ddpg_agent.py#L36
因为整个系统都用的一个sess. 所以在保存训练的weight时候，会把imitiation的权重copy一份也保存到训练ckpt中。所以在测试的时候就直接restore保存的weight就行了
