### ISSUE TITLE
(localhost:2000) failed to read data: timed out

### ISSUE THREAD

**Issue by chrisyan** [zhangfuyang/rl_CARLA#30]
hello, I tried to run  ./CarlaUE4.sh -carla-server -benchmark -fps=10 and python3 ddpg_main.py as your instruction, but I got the error, something like 
"0%|                 | 0/1000000 [00:00<?, ?it/s]
start to reset env
0%|                 | 0/1000000 [00:00<?, ?it/s]
(localhost:2000) failed to read data: timed out
0%|                 | 0/1000000 [00:00<?, ?it/s]
start to reset env
0%|                 | 0/1000000 [00:00<?, ?it/s]
(localhost:2000) connection closed
"
I am using carla 0.9.10. Could you give me any tipps？ I appreciate.

**Comment by zhangfuyang** [comment]
Oh. I remember Carla 0.8 to 0.9 is a big change. You should run with the 0.8.2 version
