### ISSUE TITLE
Carla的版本信息

### ISSUE THREAD

**Issue by Aarnnity** [zhangfuyang/rl_CARLA#31]
您好，请问您所用的Carla 0.8.2版本，能够让DDPG在多车道驾驶？并可以添加其他车辆（这些车辆的是否可以进行修改）？
      希望得到您的回复。谢谢！

**Comment by zhangfuyang** [comment]
0.8.2只有单车道，所以无法换道。可以添加其他npc车辆，但无法对他们进行控制

**Comment by Aarnnity** [comment]
> 0.8.2只有单车道，所以无法换道。可以添加其他npc车辆，但无法对他们进行控制
好的，谢谢您。

**Comment by Aarnnity** [comment]
> 0.8.2只有单车道，所以无法换道。可以添加其他npc车辆，但无法对他们进行控制

好的，谢谢您。
