### ISSUE TITLE
Bad training performance

### ISSUE THREAD

**Issue by CharlesPeng1998** [zhangfuyang/rl_CARLA#33]
Hi. I ran your training script for a few days and I got following results.
![Screenshot from 2021-05-04 09-56-55](https://user-images.githubusercontent.com/32303546/116953392-bb894a80-acbf-11eb-8cb1-4d69dcc4ae9c.png)
The agent seemed to learn something at about 1k step. Then the training curve degraded and converged at bad performance. I am wondering what may cause this to happen? Could you tell me how your pre-trained model was trained?

**Comment by zhangfuyang** [comment]
Sorry for the late reply.  Did you load pretrained weight from here https://github.com/carla-simulator/imitation-learning before training? I just used this pretrained weight to extract feature and launch ddpg_main.py.

**Comment by CharlesPeng1998** [comment]
Yes. I think the pretrained model was loaded as the printed log showed:
```
Restoring from  /media/autolab/disk_2T/jiancongpeng/repos/rl_CARLA/environment/imitation/model/model.ckpt-450000
INFO:tensorflow:Restoring parameters from /media/autolab/disk_2T/jiancongpeng/repos/rl_CARLA/environment/imitation/model/model.ckpt-450000
INFO:tensorflow:Restoring parameters from /media/autolab/disk_2T/jiancongpeng/repos/rl_CARLA/environment/imitation/model/model.ckpt-450000
```

**Comment by zhangfuyang** [comment]
mmm, not sure. Have you tried to train it again, could be caused by random parameters? I don't have a specific suggestion..
