### ISSUE TITLE
Results when training on RGB Camera

### ISSUE THREAD

**Issue by flogrammer** [zhangfuyang/rl_CARLA#5]
Hi!

Could you tell me what your results were when you ran the ddpg on the rgb camera?
Isn't the input state too complex for training directly from pixles? Did you also apply segmentation?

Thanks!

**Comment by zhangfuyang** [comment]
The histogram result is the accumulative reward that agent got from the environment, for all the experiements we used the same reward function. The reward's definition is equal to what we train for ddpg agent. Sorry that I forget the details, but for the reward part you can check the environment code. It is just about speed, turning degree, etc.
Isn't the input state too complex for training directly from pixles? --- I think it is. But I didn't try it hard. So, it's possible that getting a better result from raw input than what I had got. 
Did you also apply segmentation? No, just based on rgb camera.
