### ISSUE TITLE
What's the function of check_gradient in ActorNetwork?

### ISSUE THREAD

**Issue by anotherkey** [zhangfuyang/rl_CARLA#6]
In my opinion, μ is Actor's policy
self.action_gradients are the grad_Q of action -- ▽Q_a
self.net_params are the parameters ot ActorNet - -Θ
we want to max the performance objective J
▽J is a function of ▽Q_a and ▽μ_Θ

however, I can't understand
self.check_gradient = tf.gradients(self.outputs, self.net_params[-2])
Why use self.net_params [-2] to compute gradient? 
What's the function of check_gradient in ActorNetwork?

**Comment by zhangfuyang** [comment]
Ah, Sorry for late reply (somehow I didn't get the notification of the issues..) and sorry for the misleading..

check_gradient is useless, I just used this parameter to debug (check for gradient during training).

**Comment by anotherkey** [comment]
Got it.Thank you for your reply!
