### ISSUE TITLE
Performance in Carla 0.9.6

### ISSUE THREAD

**Issue by sheelabhadra** [zhangfuyang/rl_CARLA#7]
Hi, 
Awesome work in training DDPG from raw pixels! I am trying to run your code in version 0.9.6 of Carla. The main difference I believe between the 0.9.x versions and the stable version is the method of communication between the server and client. I made changes to your implementation and now can run your inference code (test_ddpg.py)error free. I am setting the lane intersection and off road intersection as 0. I am getting a weird driving behavior that you can see [here](https://drive.google.com/open?id=1FDVoojBuXnzOeJEtEvuTro480xYypWeC).

1. Do you know what might be possibly going wrong here?
2. How are you accessing the values for the offlane intersection and offroad intersection?

Please let me know if you want to take a look at my code. I can share with it you if that helps.

Thanks!

**Comment by zhangfuyang** [comment]
1. Are you using the the pretrained model to do the inference in 0.9 version? If so, my first guess for the reason of the weird behaviour is the different observation space between training and testing, since training environment is different from inference environment. 
2. I am not sure if 0.9 version has this measurement. In 0.8 stable version, we can directly access these values. 
![image](https://user-images.githubusercontent.com/26685632/67134226-04ed7400-f1c6-11e9-8f35-9addb113a168.png)
image from https://carla.readthedocs.io/en/0.8.4/measurements/

**Comment by sheelabhadra** [comment]
Thank you for the info regarding players measurements. These measurements are not yet available in 0.9.x versions but there are sensors to detect lane invasions and adjacent lane information which do not give the exact info (fraction/percentage of intersection) that you are using.

The observation space looks the same in the  0.8.x and 0.9.x versions, although I am not sure if there are minor differences. I was working on the 0.9.6 version since it allowed me to add custom tracks. 

Anyway, I switched to the 0.8.x version and I am trying to customize the existing maps following the steps mentioned [here](https://carla.readthedocs.io/en/stable/map_customization/). Are you aware of a way to import custom maps built using RoadRunner in the 0.8.2 (stable) version? I have posted an issue regarding the same on the carla repo but haven't received any response yet.

**Comment by zhangfuyang** [comment]
Sorry. I have no idea about custom map. I just ran the agent on provided maps (Town01, Town02)

**Comment by Aarnnity** [comment]
> 嗨，
> 从原始像素训练DDPG的出色工作！我正在尝试在Carla的0.9.6版中运行您的代码。我认为0.9.x版本和稳定版本之间的主要区别是服务器和客户端之间的通信方法。我对您的实现进行了更改，现在可以无错误地运行您的推理代码（test_ddpg.py）。我将车道交叉口和越野交叉口设置为0。您将[在这里](https://drive.google.com/open?id=1FDVoojBuXnzOeJEtEvuTro480xYypWeC)看到奇怪的驾驶行为。
> 
> 1. 您知道这里可能出什么问题吗？
> 2. 您如何访问黄麻路口和越野路口的值？
> 
> 如果您想看一下我的代码，请告诉我。如果可以的话，我可以与您分享。
> 
> 谢谢！

Hi, can you share the relevant code running on carla 0.9.6? Recently, I want to learn from this.
Hope to get your help. Thank you!
